const express =require('express')
const router=express.Router()
const UserModel=require('../model/userModel')
const {createUser,getShippingInfor,updateShippingInfor, addOrders, getOrders} =require('../controllers/userController')
router.post('/createUser',createUser)
router.get('/shippingInfor',getShippingInfor)
router.post('/updateShippingInfor',updateShippingInfor)
router.post('/addOrders',addOrders)
router.get('/orders/:userId',getOrders)
module.exports=router